version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "/base/alpine/Dockerfile",
    "/base/ubuntu/Dockerfile",
    "/java/8/temurin/Dockerfile",
    "/java/8/corretto/Dockerfile",
    "/java/11/temurin/Dockerfile",
    "/java/11/corretto/Dockerfile",
    "/java/16/temurin/Dockerfile",
    "/java/16/corretto/Dockerfile",
    "/java/17/temurin/Dockerfile",
    "/java/17/corretto/Dockerfile",
    "/java/18/temurin/Dockerfile",
    "/java/18/corretto/Dockerfile",
    "/nodejs/ubuntu/18/Dockerfile",
    "/nodejs/alpine/18/Dockerfile",
    "/nodejs/ubuntu/20/Dockerfile",
    "/nodejs/alpine/20/Dockerfile",
    "/nodejs/ubuntu/22/Dockerfile",
    "/nodejs/alpine/22/Dockerfile"
  ]