name: Build Docker Image

on: [push]

jobs:
  Linter:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Runner
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Building-Validity:
    runs-on: self-hosted
    needs: Linter
    steps:
      - uses: actions/checkout@v2
      - name: Docker Image Building Validity
        run: docker build . --file Dockerfile --tag docker-images:$(date +%s)

  Vulnerability-Checking:
    runs-on: self-hosted
    needs: Building-Validity

    steps:
      - uses: actions/checkout@v2

      - name: Setting Image Tag
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag myapp:${{ steps.vars.outputs.docker_tag }}

      - name: Running Vulnerability Test
        uses: phonito/phonito-scanner-action@master
        with:
          image: myapp:${{ steps.vars.outputs.docker_tag }}
          phonito-token: '${{ secrets.SECURITY_API }}'
          fail-level: LOW


  Layer-Two-Scan:
    runs-on: self-hosted
    needs: Vulnerability-Checking

    steps:
      - uses: actions/checkout@v2

      - name: Layer Two Scanner
        uses: brpaz/hadolint-action@master