name: Build & Push Images

on:
  workflow_dispatch:
  schedule:
    - cron: "* */24 * * *"
  push:
    branches:
      - develop

jobs:
  Alpine-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Java 8
        working-directory: ./java/8/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }} > /dev/null 2>&1
          docker build . -t quay.io/discoversquishy/dockerimages:alpine-base-dev
          docker push quay.io/discoversquishy/dockerimages:alpine-base-dev
          docker logout > /dev/null 2>&1

  Java-8-Temurin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Java 8
        working-directory: ./java/8/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }} > /dev/null 2>&1
          docker build . -t quay.io/discoversquishy/dockerimages:java8-temurin-dev
          docker push quay.io/discoversquishy/dockerimages:java8-temurin-dev
          docker logout > /dev/null 2>&1

  Java-11-Temurin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Java 11
        working-directory: ./java/11/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }} > /dev/null 2>&1
          docker build . -t quay.io/discoversquishy/dockerimages:java11-temurin-dev
          docker push quay.io/discoversquishy/dockerimages:java11-temurin-dev
          docker logout > /dev/null 2>&1