name: Lint Check

on:
  push:
      paths:
        - 'nodejs/**'
        - 'java/**'
        - 'base/**'

jobs:
  Alpine-Base-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./base/alpine/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Ubuntu-Base-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./base/ubuntu/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Ubuntu-12-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/ubuntu/12/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Ubuntu-14-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/ubuntu/14/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Ubuntu-16-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/ubuntu/16/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Ubuntu-18-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/ubuntu/18/Dockerfile
            ignore: DL3018 DL3059 DL3008
  NodeJS-Ubuntu-19-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/ubuntu/19/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Alpine-12-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/alpine/12/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Alpine-14-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/alpine/14/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Alpine-16-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/alpine/16/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  NodeJS-Alpine-18-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/alpine/18/Dockerfile
            ignore: DL3018 DL3059 DL3008
  NodeJS-Alpine-19-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./nodejs/alpine/19/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-8-Temurin:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/8/temurin/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-8-Corretto:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/8/corretto/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-11-Temurin:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/11/temurin/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-11-Corretto:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/11/corretto/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-16-Temurin:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/16/temurin/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-16-Corretto:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/16/corretto/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-17-Temurin:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/17/temurin/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-17-Corretto:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/17/corretto/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-18-Temurin:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/18/temurin/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error
  Java-18-Corretto:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: hadolint/hadolint-action@v3.0.0
          with:
            dockerfile: ./java/18/corretto/Dockerfile
            ignore: DL3018 DL3059 DL3008
            failure-threshold: error