name: Lint Check

on:
  push:
    paths:
      - 'nodejs/**'
      - 'java/**'
      - 'base/**'

jobs:
  Base-Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./base/${{ matrix.os }}/Dockerfile
          ignore: DL3018 DL3059 DL3008
          failure-threshold: error

  NodeJS-Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, alpine]
        version: [18, 20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./nodejs/${{ matrix.os }}/${{ matrix.version }}/Dockerfile
          ignore: DL3018 DL3059 DL3008

  Java-Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, alpine]
        version: [8, 11, 16, 17, 18, 19]
        distribution: [temurin, corretto]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./java/${{ matrix.os }}/${{ matrix.version }}/${{ matrix.distribution }}/Dockerfile
          ignore: DL3018 DL3059 DL3008
          failure-threshold: error