name: Java Workflow

on: push

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Runner
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Building-Validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: "java-adoptopenjdk8-hotspot"
          tags: "latest ${{ github.sha }}"
          dockerfiles: |
            ./java/Dockerfile

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/quay-user
          username: quay-user
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"