name: Java Workflow

on: push

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Runner
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Building-Validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Image Building Validity
        run: docker build ./java/ --tag java:$(date +%s)

      - name: Publish
        uses: docker/build-push-action@v2
        with:
          path: ./java/Dockerfile
          registry: quay.io
          repository: discoversquishy/dockerimages
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: "java8-adoptopenjdk-hotspot"
