name: Java Workflow

on: push

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Runner
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Building-Validity:
    runs-on: ubuntu-latest
    name: Build & Push
    steps:
      - name: Login to Quay Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./java/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            discoversquishy/java8:java8