name: Java Workflow

on: push

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Runner
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Building-Validity:
    runs-on: ubuntu-latest
    name: Build & Push
    env: { CONTAINER_REPO: quay.io/discoversquishy/dockerimages }
    steps:
      - uses: actions/checkout@v2
      - name: Log into the container repository
        run: |
          ${{ secrets.DOCKER_LOGIN }}
      - name: Build all of the container images
        working-directory: ./java
        run: |
            docker build . --file Dockerfile --tag java8-adoptopenjdk
      - name: Push the images
        if: github.ref == 'refs/heads/main'
        run: |
            name="$CONTAINER_REPO:discoversquishy/dockerimages"
            docker tag "java8-adoptopenjdk" "$name"
            docker push "$name"
            name="$name-${{ github.sha }}"
            docker tag "java8-adoptopenjdk" "$name"
            docker push "$name"
