name: Lint Check

on:
  push:
      branches:
        - develop

jobs:
  Alpine-Base-Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: hadolint/hadolint-action@v1.6.0
          with:
            dockerfile: ./base/alpine/Dockerfile
            failure-threshold: error
            config: ./hadolint.yml
