name: Release Build & Push

on:
  push:
      branches:
        - main

jobs:
  # Alpine Base Building
  Alpine-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push Alpine Base
        working-directory: ./base/alpine/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx build --push \
            --tag quay.io/discoversquishy/dockerimages:alpine-base --pull --no-cache \
            --platform linux/amd64,linux/arm/v8,linux/arm64,linux/ppc64le .
          docker logout > /dev/null 2>&1

  # Ubuntu Base Building
  Ubuntu-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push Ubuntu Base
        working-directory: ./base/ubuntu/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx build --push \
            --tag quay.io/discoversquishy/dockerimages:ubuntu-base --pull --no-cache \
            --platform linux/amd64,linux/arm/v8,linux/arm64,linux/ppc64le .
          docker logout > /dev/null 2>&1

  ## Eclipse Temurin Building
  Java-8-Temurin:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 8 Temurin
        working-directory: ./java/8/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java8-temurin --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java8-temurin
          docker logout > /dev/null 2>&1

  Java-11-Temurin:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 11 Temurin
        working-directory: ./java/11/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java11-temurin --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java11-temurin
          docker logout > /dev/null 2>&1

  Java-16-Temurin:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 16 Temurin
        working-directory: ./java/16/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java16-temurin --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java16-temurin
          docker logout > /dev/null 2>&1

  Java-17-Temurin:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 17 Temurin
        working-directory: ./java/17/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java17-temurin --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java17-temurin
          docker logout > /dev/null 2>&1

  Java-18-Temurin:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 18 Temurin
        working-directory: ./java/18/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java18-temurin --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java18-temurin
          docker logout > /dev/null 2>&1

  Java-19-Temurin:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 18 Temurin
        working-directory: ./java/18/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java19-temurin --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java19-temurin
          docker logout > /dev/null 2>&1

  ## Amazon Corretto Building
  Java-8-Corretto:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 8 Corretto
        working-directory: ./java/8/corretto/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java8-corretto --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java8-corretto
          docker logout > /dev/null 2>&1

  Java-11-Corretto:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 11 Corretto
        working-directory: ./java/11/corretto/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java11-corretto --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java11-corretto
          docker logout > /dev/null 2>&1

  Java-16-Corretto:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 16 Corretto
        working-directory: ./java/17/corretto/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java16-corretto --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java16-corretto
          docker logout > /dev/null 2>&1

  Java-17-Corretto:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 17 Corretto
        working-directory: ./java/17/corretto/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java17-corretto --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java17-corretto
          docker logout > /dev/null 2>&1

  Java-18-Corretto:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 17 Corretto
        working-directory: ./java/18/corretto/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java18-corretto --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java18-corretto
          docker logout > /dev/null 2>&1

  Java-19-Corretto:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Java 19 Corretto
        working-directory: ./java/19/corretto/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:java19-corretto --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:java19-corretto
          docker logout > /dev/null 2>&1

  ## Ubuntu NodeJS Building
  Node-12-Ubuntu:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-12 Ubuntu
        working-directory: ./nodejs/ubuntu/12/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-12-ubuntu --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-12-ubuntu
          docker logout > /dev/null 2>&1

  Node-14-Ubuntu:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-14 Ubuntu
        working-directory: ./nodejs/ubuntu/14/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-14-ubuntu --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-14-ubuntu
          docker logout > /dev/null 2>&1

  Node-16-Ubuntu:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-16 Ubuntu
        working-directory: ./nodejs/ubuntu/16/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-16-ubuntu --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-16-ubuntu
          docker logout > /dev/null 2>&1

  Node-18-Ubuntu:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-18 Ubuntu
        working-directory: ./nodejs/ubuntu/18/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-18-ubuntu --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-18-ubuntu
          docker logout > /dev/null 2>&1

  Node-19-Ubuntu:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-19 Ubuntu
        working-directory: ./nodejs/ubuntu/19/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-19-ubuntu --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-19-ubuntu
          docker logout > /dev/null 2>&1

  Node-20-Ubuntu:
    runs-on: ubuntu-latest
    needs: Ubuntu-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-20 Ubuntu
        working-directory: ./nodejs/ubuntu/20/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages-dev:node-20-ubuntu --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages-dev:node-20-ubuntu
          docker logout > /dev/null 2>&1

  ## Alpine NodeJS Building
  Node-12-Alpine:
    runs-on: ubuntu-latest
    needs: Alpine-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-12 Alpine
        working-directory: ./nodejs/alpine/12/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-12-alpine --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-12-alpine
          docker logout > /dev/null 2>&1

  Node-14-Alpine:
    runs-on: ubuntu-latest
    needs: Alpine-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-14 Alpine
        working-directory: ./nodejs/alpine/14/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-14-alpine --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-14-alpine
          docker logout > /dev/null 2>&1

  Node-16-Alpine:
    runs-on: ubuntu-latest
    needs: Alpine-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-16 Alpine
        working-directory: ./nodejs/alpine/16/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-16-alpine --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-16-alpine
          docker logout > /dev/null 2>&1

  Node-18-Alpine:
    runs-on: ubuntu-latest
    needs: Alpine-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-18 Alpine
        working-directory: ./nodejs/alpine/18/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-18-alpine --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-18-alpine
          docker logout > /dev/null 2>&1

  Node-19-Alpine:
    runs-on: ubuntu-latest
    needs: Alpine-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-19 Alpine
        working-directory: ./nodejs/alpine/19/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages:node-19-alpine --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages:node-19-alpine
          docker logout > /dev/null 2>&1

  Node-20-Alpine:
    runs-on: ubuntu-latest
    needs: Alpine-Base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push Node-19 Alpine
        working-directory: ./nodejs/alpine/20/
        run: |
          ${{ secrets.QUAY_LOGIN }}
          docker build . -t quay.io/discoversquishy/dockerimages-dev:node-20-alpine --pull --no-cache
          docker push quay.io/discoversquishy/dockerimages-dev:node-20-alpine
          docker logout > /dev/null 2>&1