name: Build & Push Images

on:
  push:
      branches:
        - main

jobs:
  Alpine-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Java 8
        working-directory: ./java/8/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }} > /dev/null 2>&1
          docker build . -t quay.io/discoversquishy/dockerimages:alpine-base
          docker push quay.io/discoversquishy/dockerimages:alpine-base
          docker logout > /dev/null 2>&1

  Java-8-Temurin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Java 8
        working-directory: ./java/8/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }} > /dev/null 2>&1
          docker build . -t quay.io/discoversquishy/dockerimages:java8-temurin
          docker push quay.io/discoversquishy/dockerimages:java8-temurin
          docker logout > /dev/null 2>&1

  Java-11-Temurin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Java 11
        working-directory: ./java/11/temurin/
        run: |
          ${{ secrets.QUAY_LOGIN }} > /dev/null 2>&1
          docker build . -t quay.io/discoversquishy/dockerimages:java11-temurin
          docker push quay.io/discoversquishy/dockerimages:java11-temurin
          docker logout > /dev/null 2>&1