name: Scripts Update

on:
  push:
      paths:
        - 'scripts/**'

jobs:
  Temurin-Download-Update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Upload Script to CDN
      env:
        SCRIPT_FILENAME: temurin-download.sh
      run: ${{ secrets.UPDATECDN }}